spring.application.name=api-gateway

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/users/**,/api/v1/user/**,/internal/users/**

spring.cloud.gateway.server.webmvc.routes[1].id=authentication-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://AUTHENTICATION-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/auths/**

spring.cloud.gateway.server.webmvc.routes[2].id=category-service
spring.cloud.gateway.server.webmvc.routes[2].url=lb://CATEGORY-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/categories/**,/api/v1/category/**