spring.application.name=authentication-service

server.port=8082

eureka.client.service-url.defaultZone=http://eurekaserver:8761/eureka

jwt.secret=SEf3hmhmSCb0FUTbXGseGrXC9MfFJwQYbDrdv59lZiT
jwt.expiration=30

internal.api-key=OMloV3AVdNwBoOTdK2btrcWPJ7NGq273

# ACTUATOR
management.health.refresh.enabled=true

# PROMETHEUS
management.endpoints.web.exposure.include=*,prometheus
management.endpoint.health.probes.enabled=true