spring.application.name=category-service

server.port=8083

# DATABASE SOURCE
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.name=postgres
spring.datasource.username=postgres
spring.datasource.password=password

# JPA
spring.jpa.

# SECRET
jwt.secret=SEf3hmhmSCb0FUTbXGseGrXC9MfFJwQYbDrdv59lZiT
